//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use chrono::NaiveDate;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "front_matter")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub date: NaiveDate,
    pub slug: String,
    pub tags: Vec<String>,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::markdown::Entity")]
    Markdown,
}

impl Related<super::markdown::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Markdown.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
