//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "markdown")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub front_matter_id: i32,
    #[sea_orm(column_type = "Text")]
    pub html: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::front_matter::Entity",
        from = "Column::FrontMatterId",
        to = "super::front_matter::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FrontMatter,
}

impl Related<super::front_matter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FrontMatter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
